name: Release CI

on:
  push:
    tags:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: 📡 Checkout
        uses: actions/checkout@v4

      # Configures NodeJS.
      - name: ⚙️ Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: devops-actions/variable-substitution@v1.2
        with:
          files: "module.json"
        env:
          version: ${{github.ref_name}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/download/${{github.ref_name}}/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.ref_name}}/module.zip

      # Creates the ZIP artifact.
      - name: 📦 Create ZIP Archive
        run: |
          mkdir dist
          cp module.json dist/module.json
          cp -r src/* dist/
          cd dist/
          zip -r ../module.zip *

      # Creates the release with its artifacts and description.
      - name: 🚀 Update Release with Artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          tag: ${{ github.ref_name }}
          artifacts: './module.zip, ./module.json'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Publishes the release to the FoundryVTT's package repository.
      - name: 🚩 Publish Module to FoundryVTT Website
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.FVTT_PACKAGE_API_KEY }}
          manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.ref_name}}/module.json
